---
#
# Ansible managed
#
repository:
  description: Install and configure zabbix_repository on your system.
  homepage: https://robertdebock.nl/
  topics: zabbix, repository, monitoring, ansible, molecule, playbook
